controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login
password_request:
    path: /password/request
    controller: App\Controller\ResetPasswordController::requestReset
# config/routes.yaml
index:
    path: /
    controller: App\Controller\StarterPageController::index

starter_page:
    path: /starter_page
    controller: App\Controller\StarterPageController::starterPage