# config/services.yaml
parameters:
    profile_image_directory: '%kernel.project_dir%/public/uploads/profile_images'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true  # <---- Assure-toi que cette ligne est bien présente

    App\Service\SmsService:
        arguments:
            $nexmoApiKey: '%env(NEXMO_API_KEY)%'
            $nexmoApiSecret: '%env(NEXMO_API_SECRET)%'
            $brandName: '%env(NEXMO_BRAND_NAME)%'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']  # <---- Correction d'indentation ici

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
